Feature: Get boleto info
brazilian-utils/brazilian-utils pull request #243
Opened 2021-06-11 00:49 UTC by LucasCarrias

## References

[Feature request] Get "boleto" information from digitable line #239

## Objectives

Create getBoletoInfo function to get data from a valid boleto.

Usage example:

```javascript
>> getBoletoInfo('23793381286006069409261000063307486470000004200');

>> {
    valueInCents: 4200,
    expirationDate: 2021-06-10T03:00:00.000Z,
    bankCode: '237'
   }
```

## Changes

* Create getValueInCents function
* Create getExpirationDate function
* Create getBankCode function
* Create Boleto interface
* Create getInfo function and export it as getBoletoInfo
* Add getBoletoInfo to docs

## Notes

The `currency` field mentioned at #239 hasn't been added because, most of cases, the brazilian payment method will be charged with BRL values.

2021-06-11 14:58 UTC, hyanmandian commented
Nice job @LucasCarrias ! @all-contributors please add @LucasCarrias for docs, tests, and code.

2021-06-11 15:05 UTC, hyanmandian requested changes

2021-06-11 15:05 UTC, hyanmandian commented on src/utilities/boleto/index.ts
> +  const valueStartIndex = digits.length - 10;
what do you think to create a variable to store the "10" value and give it a name?

2021-06-11 15:05 UTC, hyanmandian commented on src/utilities/boleto/index.ts
> +  const firstDay = new Date(1997, 9, 7);
it can be a constant outside of this function called `BANCO_CENTRAL_BASE_DATE` (or something that you think is better)

2021-06-11 15:05 UTC, hyanmandian commented on src/utilities/boleto/index.ts
> +  const daysSinceFirstDay = digitableLine.substr(digitableLine.length - 14, 4);
what do you think to put "14" and "4" in a variable and give a name to these numbers?

2021-06-11 15:05 UTC, hyanmandian commented on src/utilities/boleto/index.ts
> +  const dateSinceFirstDay = new Date(Number(daysSinceFirstDay) * 24 * 60 * 60 * 1000);
what do you think to put "24 * 60 * 60 * 1000" in a variable?

2021-06-11 17:13 UTC, LucasCarrias commented
@hyanmandian Thanks for the reviews! I'll follow your recommendations.

2021-06-11 20:21 UTC, hyanmandian approved these changes

2021-06-11 20:24 UTC, hyanmandian commented
As soon I have time I will merge and publish your utility.

 Thanks for your contribution and welcome aboard!

2025-01-26 06:01 UTC, closed without merging

2025-01-26 06:01 UTC, hyanmandian commented
Fala @lucascarrias tudo certo? Cara, to fazendo um refactoring ta lib inteira e vou incluir sua alteracao la! https://github.com/brazilian-utils/brazilian-utils/pull/398 @diasbruno pode ficar tranquilo que incluirei sua sugestao de melhoria tb!

Sintam-se a vontade a fazer o review se quiserem!