feat: new cnpj alphanumeric
brazilian-utils/brazilian-utils pull request #369
Opened 2024-07-01 01:42 UTC by fxamauri

Adiciona validação e formatação do novo CNPJ alfanumérico

## Pontos de Atenção:
- Tecnicamente, estamos introduzindo uma "breaking change" na validação do CNPJ, pois anteriormente não aceitávamos caracteres que não fossem números (havia testes validando isso que foram alterados nesta pr).
- Agora, passamos a permitir caracteres alfanuméricos, o que quebra o comportamento anterior.
- Precisamos considerar que essa mudança pode impactar nas versões anteriores a esta pr, que dependem da validação estritamente numérica.
- Talvez seja interessante adicionar uma flag nas funções alteradas para indicar que a validação deve considerar o novo formato alfanumérico.

Fico à disposição para pensarmos na melhor maneira de implementar isso.

resolve #361

2024-07-23 20:39 UTC, hyanmandian commented
Valeu demais @fxamauri ! Eu vou tentar arrumar um tempo essa semana pra fazer o review do teu PR e publica-lo. Muito obrigado!

2024-07-23 20:44 UTC, hyanmandian commented on src/utilities/email/index.ts
> +  /^([!#$%&'*+\-/=?^_`{|}~]{0,1}([a-zA-Z0-9][!#$%&'*+\-/=?^_`{|}~.]{0,1})+)@(([a-zA-Z0-9][-.]{0,1})+)([.]{1}[a-zA-Z0-9]+)$/;
Nao sei teve change aqui, mas tu poderia desfazer?

2024-07-23 20:45 UTC, hyanmandian commented on src/utilities/cnpj/index.ts
> +function generateChecksumCNPJ(base: string, weight: number[]): number {
Ja que o generateChecksum n ta mais sendo importado aqui, acho que daria pra manter o mesmo nome, oq tu acha?

2024-07-23 20:45 UTC, hyanmandian commented on src/utilities/cnpj/index.ts
> +}
Nao acho que seja necessario separar isso numa funcao tendo em vista que eh algo usado em apenas um lugar

2024-07-23 20:45 UTC, hyanmandian commented on src/utilities/cnpj/index.ts
> +  let digits = onlyValidCNPJAlphanumeric(valueCNPJUppercased);
```suggestion
  let digits = onlyValidCNPJAlphanumeric(String(cnpj).toUpperCase());
```

2024-07-23 20:46 UTC, hyanmandian commented on src/utilities/cnpj/index.ts
> +const VALID_CHARS_CNPJ = '0123456789ABCDFGHIJKLMNPQRSVWXYZ';
```suggestion
const VALID_CHARS = '0123456789ABCDFGHIJKLMNPQRSVWXYZ';
```

2024-07-23 20:48 UTC, hyanmandian commented on src/utilities/cnpj/index.ts
>  }
Eu nao sei um bom nome pra isso, mas pra evitar qualquer breaking change, acredito que de pra utilizar os options pra passar uma flag dizendo qual versao sera utilizada. A gente pode setar a versao antiga como a default, assim a gente nao quebra nada. Oq tu acha?

```suggestion
export interface FormatCnpjOptions {
  pad?: boolean;
  version?: "1" | "2"
}
```

2024-07-23 20:48 UTC, hyanmandian commented on src/utilities/cnpj/index.ts
>  }
Nesse caso, a gente teria que atualizar a doc tambem pra refletir isso

2024-07-23 20:49 UTC, hyanmandian requested changes
Acredito que a change que eu sugeri referente ao options faca o restante do codigo mudar para poder suportar as duas versoes, dessa forma vou limitar meu review aqui ate que a gente resolva essa questao, tudo bem?

2024-07-29 13:05 UTC, fxamauri commented on src/utilities/cnpj/index.ts
>  }
feito os ajustes pedidos, e atualizado doc.

2024-07-29 18:50 UTC, hyanmandian commented on src/utilities/cnpj/index.ts
> +export type CnpjVersions = '1' | '2';
```suggestion
export type CnpjVersions = '1' | '2' | 1 | 2;
```

2024-07-29 18:50 UTC, hyanmandian commented on src/utilities/cnpj/index.ts
> +  // botar um type Vesions
acho q n precisa mais desse comment, certo?

2024-07-29 18:50 UTC, hyanmandian commented on src/utilities/cnpj/index.ts
> +  const validValue = options.version === '2' ? onlyValidCNPJAlphanumeric(cnpj) : onlyNumbers(cnpj);
```suggestion
  const validValue = options.version == 2 ? onlyValidCNPJAlphanumeric(cnpj) : onlyNumbers(cnpj);
```
dessa forma se passar 2 number ou string vai funcionar igual

2024-07-30 16:59 UTC, fxamauri commented on src/utilities/cnpj/index.ts
> +export type CnpjVersions = '1' | '2';
boaa!

2025-01-26 04:34 UTC, hyanmandian commented
@fxamauri estou trabalhando num refactoring do projeto, ja vou incluir sua mudanca nesse refactoring. Desculpa nao ter te dado retorno antes, mas agora estou voltando a manter o projeto!

2025-01-26 05:54 UTC, hyanmandian commented
Ja inclui no refactor!

https://github.com/brazilian-utils/brazilian-utils/pull/398

2025-01-26 05:54 UTC, closed without merging